### ISSUE TITLE
insteonplm binding does not work with openhab2

### ISSUE THREAD

**Issue by jtmoderate876** [openhab/openhab#3922]
I've got OH2b1 build #106 (2016.01.27) working with ecobee and a few things but...

I get the following error for the insteonplm binding after a couple minutes which worries me that the new, more rigorous requirements of eclipse or whatever means it needs to be patched/fixed.

```
Exception in thread "Thread-36" java.lang.NoSuchMethodError: org.apache.http.impl.client.DefaultHttpClient.execute(Lorg/apache/http/client/methods/HttpUriRequest;)Lorg/apache/http/client/methods/CloseableHttpResponse;
    at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.getURL(HubIOStream.java:213)
    at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.bufferStatus(HubIOStream.java:108)
    at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.poll(HubIOStream.java:156)
    at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.run(HubIOStream.java:226)
    at java.lang.Thread.run(Thread.java:744)
Exception in thread "/hub2/Mirabell:BAxfhx6l@192.168.1.120:25105,poll_time=1000 Writer" java.lang.NoSuchMethodError: org.apache.http.impl.client.DefaultHttpClient.execute(Lorg/apache/http/client/methods/HttpUriRequest;)Lorg/apache/http/client/methods/CloseableHttpResponse;
    at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.getURL(HubIOStream.java:213)
    at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.bufferStatus(HubIOStream.java:108)
    at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.poll(HubIOStream.java:156)
    at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.write(HubIOStream.java:139)
    at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream$HubOutputStream.flushBuffer(HubIOStream.java:308)
    at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream$HubOutputStream.write(HubIOStream.java:302)
    at java.io.OutputStream.write(OutputStream.java:75)
    at org.openhab.binding.insteonplm.internal.driver.IOStream.write(IOStream.java:68)
    at org.openhab.binding.insteonplm.internal.driver.Port$IOStreamWriter.run(Port.java:421)
    at java.lang.Thread.run(Thread.java:744)
```

watoumaintainer14h 1 
jtmoderate876:
Exception in thread "Thread-36" java.lang.NoSuchMethodError: org.apache.http.impl.client.DefaultHttpClient.execute(Lorg/apache/http/client/methods/HttpUriRequest;)Lorg/apache/http/client/methods/CloseableHttpResponse;
    at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.getURL(HubIOStream.java:213)

In the IDE, the call to execute shows this warning:

Discouraged access: The method 'CloseableHttpClient.execute(HttpUriRequest)' is not API (restriction on required library '[...]/openhab/ws/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/org.apache.httpcomponents.httpclient_4.3.6.v201411290715.jar')
The package org.apache.http.impl.client is marked "x-internal:=true" in MANIFEST.MF, and the IDE marks the Apache HTTP classes used as deprecated.

I think code changes are needed to the InsteonPLM binding so it uses different HTTP classes that are supported in both OH1 and OH2.

See:
https://community.openhab.org/t/insteonplm-in-oh2-and-some-ui-in-oh2/3905/5
##

**Comment by watou** [comment]
Thanks!

**Comment by kaikreuzer** [comment]
This is indeed an internal and deprecated class that must not be used within the binding.
See also http://www.mkyong.com/java/the-type-defaulthttpclient-is-deprecated/

**Comment by watou** [comment]
Referencing the solution you linked above, it says to use HttpClientBuilder, but that class 
```
import org.apache.http.impl.client.HttpClientBuilder;
...
 		HttpClient client = HttpClientBuilder.create().build();
```
is in the same package `org.apache.http.impl.client` as `DefaultHttpClient`, which is marked `x-internal`  in the bundle's Export-Package in MANIFEST.MF:
```
...,org.apache.http.impl.client;version="4.3.6";x-internal:=true,...
```
which I think Karaf prevents the class loading, whereas Equinox doesn't.  Karaf would otherwise load deprecated classes, right?

head of MANIFEST.MF:
```
Manifest-Version: 1.0
Implementation-Vendor: The Apache Software Foundation
X-Compile-Target-JDK: 1.5
Bundle-RequiredExecutionEnvironment: J2SE-1.5
Built-By: oleg
Bundle-Version: 4.3.6.v201411290715
X-Compile-Source-JDK: 1.5
Specification-Title: HttpComponents Apache HttpClient
Specification-Version: 4.3.6
Specification-Vendor: The Apache Software Foundation
Build-Jdk: 1.7.0_21
Bundle-ClassPath: .
Implementation-Build: tags/4.3.6-RC1/httpclient@r1598881; 2014-05-31 1
 7:18:30+0200
Created-By: Apache Maven 3.0.5
Import-Package: javax.crypto,javax.crypto.spec,javax.net,javax.net.ssl
 ,javax.security.auth.x500,net.sf.ehcache;resolution:=optional,net.spy
 .memcached;resolution:=optional,org.apache.commons.codec.binary;versi
 on="1.6.0",org.apache.commons.logging;version="1.1.1",org.apache.http
 ;version="4.3.3",org.apache.http.concurrent;version="4.3.3",org.apach
 e.http.config;version="4.3.3",org.apache.http.entity;version="4.3.3",
 org.apache.http.impl;version="4.3.3",org.apache.http.impl.io;version=
 "4.3.3",org.apache.http.io;version="4.3.3",org.apache.http.message;ve
 rsion="4.3.3",org.apache.http.params;version="4.3.3",org.apache.http.
 pool;version="4.3.3",org.apache.http.protocol;version="4.3.3",org.apa
 che.http.util;version="4.3.3",org.ietf.jgss
Implementation-Vendor-Id: org.apache
Bundle-SymbolicName: org.apache.httpcomponents.httpclient
Eclipse-SourceReferences: scm:cvs:pserver:dev.eclipse.org:/cvsroot/too
 ls:org.eclipse.orbit/org.apache.httpcomponents.httpclient;tag=v201411
 290715
Export-Package: org.apache.http.auth;version="4.3.6"; uses:="org.apach
 e.http.protocol,  org.apache.http.params,  org.apache.http.config,  o
 rg.apache.http",org.apache.http.auth.params;version="4.3.6";uses:="or
 g.apache.http.params",org.apache.http.client;version="4.3.6"; uses:="
 org.apache.http.protocol,  org.apache.http.params,  org.apache.http.c
 onn.routing,  org.apache.http.conn,  org.apache.http.cookie,  org.apa
 che.http.client.methods,  org.apache.http,  org.apache.http.auth",org
 .apache.http.client.cache;version="4.3.6";uses:="org.apache.http.prot
 ocol,org.apache.http.client.protocol,org.apache.http",org.apache.http
 .client.config;version="4.3.6";uses:="org.apache.http",org.apache.htt
 p.client.entity;version="4.3.6";uses:="org.apache.http.entity,org.apa
 che.http",org.apache.http.client.fluent;version="4.3.6"; uses:="org.a
 pache.http.message,  org.apache.http.conn.scheme,  org.apache.http.en
 tity,  org.apache.http.impl.conn,  org.apache.http.client,  org.apach
 e.http.client.config,  org.apache.http.client.methods,  org.apache.ht
 tp.auth,  org.apache.http.concurrent,  org.apache.http",org.apache.ht
 tp.client.methods;version="4.3.6"; uses:="org.apache.http.conn,  org.
 apache.http.message,  org.apache.http.params,  org.apache.http.client
 .config,  new org.apache.http.client.methods,  org.apache.http.concur
 rent,  org.apache.http",org.apache.http.client.params;version="4.3.6"
 ; uses:="org.apache.http.auth.params,  org.apache.http.conn.params,  
 org.apache.http.params,  org.apache.http.cookie.params,  org.apache.h
 ttp.client.config,  org.apache.http",org.apache.http.client.protocol;
 version="4.3.6"; uses:="org.apache.commons.logging,  org.apache.http.
 cookie,  org.apache.http.protocol,  org.apache.http.config,  org.apac
 he.http.client.config,  org.apache.http.client,  org.apache.http.conn
 .routing,  org.apache.http.auth,  org.apache.http",org.apache.http.cl
 ient.utils;version="4.3.6";uses:="org.apache.http.client,org.apache.h
 ttp.client.methods,org.apache.http",org.apache.http.conn;version="4.3
 .4"; uses:="org.apache.http.protocol,  org.apache.http.conn.scheme,  
 org.apache.http.params,  org.apache.http.entity,  org.apache.http.con
 fig,  javax.net.ssl,  org.apache.http.conn.routing,  org.apache.http.
 concurrent,  org.apache.http",org.apache.http.conn.params;version="4.
 3.4";uses:="org.apache.http.params,org.apache.http.conn.routing,org.a
 pache.http",org.apache.http.conn.routing;version="4.3.6";uses:="org.a
 pache.http.protocol,org.apache.http",org.apache.http.conn.scheme;vers
 ion="4.3.6";uses:="org.apache.http.params,org.apache.http",org.apache
 .http.conn.socket;version="4.3.6";uses:="org.apache.http.protocol,org
 .apache.http",org.apache.http.conn.ssl;version="4.3.6"; uses:="org.ap
 ache.http.conn.socket,  org.apache.http.protocol,  org.apache.http.co
 nn.scheme,  org.apache.http.params,  javax.net.ssl,  org.apache.http"
 ,org.apache.http.conn.util;version="4.3.6",org.apache.http.cookie;ver
 sion="4.3.6"; uses:="org.apache.http.protocol,  org.apache.http.param
 s,  org.apache.http.config,  org.apache.http",org.apache.http.cookie.
 params;version="4.3.6";uses:="org.apache.http.params",org.apache.http
 .entity.mime;version="4.3.6";uses:="org.apache.http.entity.mime.conte
 nt,org.apache.http.entity,org.apache.http",org.apache.http.entity.mim
 e.content;version="4.3.6";uses:="org.apache.http.entity",org.apache.h
 ttp.impl.auth;version="4.3.6";x-internal:=true; uses:="org.apache.htt
 p.protocol,  org.apache.commons.logging,  org.apache.http.params,  or
 g.apache.http.client,  org.ietf.jgss,  org.apache.http.util,  org.apa
 che.http.auth,  org.apache.http",org.apache.http.impl.client;version=
 "4.3.6";x-internal:=true; uses:="org.apache.http.conn.socket,  org.ap
 ache.http.protocol,  org.apache.commons.logging,  org.apache.http.ent
 ity,  org.apache.http.client,  org.apache.http.conn.routing,  org.apa
 che.http.conn,  org.apache.http.cookie,  org.apache.http.impl.execcha
 in,  org.apache.http.impl.auth,  org.apache.http.client.config,  java
 x.net.ssl,  org.apache.http.message,  org.apache.http.conn.scheme,  o
 rg.apache.http.pool,  org.apache.http.params,  org.apache.http.conn.s
 sl,  org.apache.http.config,  org.apache.http.client.methods,  org.ap
 ache.http,  org.apache.http.auth,  org.apache.http.concurrent",org.ap
 ache.http.impl.client.cache;version="4.3.6";x-internal:=true,org.apac
 he.http.impl.client.cache.ehcache;version="4.3.6";x-internal:=true,or
 g.apache.http.impl.client.cache.memcached;version="4.3.6";x-internal:
 =true,org.apache.http.impl.conn;version="4.3.6";x-internal:=true; use
 s:="org.apache.http.message,  org.apache.http.io,  org.apache.http.pr
 otocol,  org.apache.http.impl.io,  org.apache.commons.logging,  org.a
 pache.http.conn.scheme,  org.apache.http.pool,  org.apache.http.impl,
   org.apache.http.params,  org.apache.http.entity,  org.apache.http.c
 onn.routing,  org.apache.http.conn,  org.apache.http.config,  javax.n
 et.ssl,  org.apache.http.util,  org.apache.http",org.apache.http.impl
 .conn.tsccm;version="4.3.6";x-internal:=true; uses:="org.apache.commo
 ns.logging,  org.apache.http.conn.scheme,  org.apache.http.conn.param
 s,  org.apache.http.params,  org.apache.http.impl.conn,  org.apache.h
 ttp.conn.routing,  org.apache.http.conn",org.apache.http.impl.cookie;
 version="4.3.6";x-internal:=true; uses:="org.apache.http.message,  or
 g.apache.http.protocol,  org.apache.http.cookie,  org.apache.http.par
 ams,  org.apache.http.util,  org.apache.http",org.apache.http.impl.ex
 ecchain;version="4.3.6";x-internal:=true; uses:="org.apache.http.prot
 ocol,  org.apache.commons.logging,  org.apache.http.params,  org.apac
 he.http.entity,  org.apache.http.client,  org.apache.http.conn.routin
 g,  org.apache.http.client.protocol,  org.apache.http.conn,  org.apac
 he.http.client.methods,  org.apache.http.auth,  org.apache.http.concu
 rrent,  org.apache.http"
url: http://hc.apache.org/httpcomponents-client
Bundle-Vendor: %Bundle-Vendor
Bundle-Name: %Bundle-Name
Archiver-Version: Plexus Archiver
Implementation-Title: HttpComponents Apache HttpClient
Implementation-Version: 4.3.6
Bundle-ManifestVersion: 2

Name: org/apache/http/impl/conn/SystemDefaultRoutePlanner.class
SHA1-Digest: A3eDBHqTgEBI8mVoS3d2qljHWvs=
...
```

**Comment by kaikreuzer** [comment]
> but that class is in the same package org.apache.http.impl.client as DefaultHttpClient

Good point, I didn't notice that.

> Karaf would otherwise load deprecated classes, right?

Right.

But there must be some good reason why the bundle declares the package to be internal - this is clearly a sign that it must not be used and there should be an official alternative...?

**Comment by watou** [comment]
> But there must be some good reason why the bundle declares the package to be internal

Not necessarily.  Maybe they just wanted to flag it in the IDE?

>  this is clearly a sign that it must not be used and there should be an official alternative...?

Short of finding or making a "promiscuous" version of the JAR with the `x-internal` flags removed, yes.

**Comment by kaikreuzer** [comment]
Looking at the exception in https://github.com/openhab/openhab/issues/3922#issue-129984286, I actually doubt that this is in any way related tot he x-internal package? It throws a NoSuchMethodError, which sounds to me rather that this is a different (incompatible) version of the Apache HTTP library than that of openHAB 1.

**Comment by watou** [comment]
I think that's it!  From my openHAB 1.8.0 install:
```
./server/plugins/org.apache.httpcomponents.httpclient_4.1.3.v201209201135.jar
./server/plugins/org.apache.httpcomponents.httpcore_4.1.4.v201203221030.jar
```

**Comment by kaikreuzer** [comment]
But it is not nice at all of Apache HTTP to break backward compatibility from 4.1 to 4.3...
I now fear that adapting the code to work with 4.3 might mean that it stops working for 4.1 (and thus on OH1.8 runtime).
We could package the version 4.1 with either the InsteonPLM binding feature or the compat1x feature. We would then require a version constraint on the package import to say that it must be <4.2, so that the OSGi framework resolves the correct version for the binding. This should hopefully work...

**Comment by watou** [comment]
The [Insteon PLM MANIFEST.MF](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.insteonplm/META-INF/MANIFEST.MF) has `Require-Bundle: org.apache.httpcomponents.httpcore` that should be removed, and should the MANIFEST.MF be changed to:
```
Import-Package: ...
 org.apache.http="[4.1,4.2)",
 org.apache.http.auth;version="[4.1,4.2)",
 org.apache.http.client;version="[4.1,4.2)",
 org.apache.http.client.methods;version="[4.1,4.2)",
 org.apache.http.impl.client;version="[4.1,4.2)",
 org.apache.http.params;version="[4.1,4.2)",
 org.apache.http.util="[4.1.4,4.2)",
...
```

**Comment by kaikreuzer** [comment]
Yes and the feature should then add this old version of the library.

**Comment by watou** [comment]
Maybe the insteonplm binding should just include its own copies in its lib directory, like what seems to have been a popular approach so far :worried: 
```
openhab/bundles/binding/org.openhab.binding.cups/lib/httpclient-4.1.3.jar
openhab/bundles/binding/org.openhab.binding.cups/lib/httpclient-cache-4.1.3.jar
openhab/bundles/binding/org.openhab.binding.cups/lib/httpcore-4.1.4.jar
openhab/bundles/binding/org.openhab.binding.cups/lib/httpmime-4.1.3.jar
openhab/bundles/binding/org.openhab.binding.freebox/lib/httpclient-4.3.1.jar
openhab/bundles/binding/org.openhab.binding.freebox/lib/httpcore-4.3.2.jar
openhab/bundles/binding/org.openhab.binding.freebox/lib/httpmime-4.3.1.jar
openhab/bundles/binding/org.openhab.binding.fritzboxtr064/lib/fluent-hc-4.4.1.jar
openhab/bundles/binding/org.openhab.binding.fritzboxtr064/lib/httpclient-4.4.1.jar
openhab/bundles/binding/org.openhab.binding.fritzboxtr064/lib/httpclient-cache-4.4.1.jar
openhab/bundles/binding/org.openhab.binding.fritzboxtr064/lib/httpclient-win-4.4.1.jar
openhab/bundles/binding/org.openhab.binding.fritzboxtr064/lib/httpcore-4.4.1.jar
openhab/bundles/binding/org.openhab.binding.fritzboxtr064/lib/httpmime-4.4.1.jar
openhab/bundles/binding/org.openhab.binding.ihc/lib/org.apache.httpcomponents.httpclient_4.4.1.jar
openhab/bundles/binding/org.openhab.binding.ihc/lib/org.apache.httpcomponents.httpcore_4.4.1.jar
openhab/bundles/binding/org.openhab.binding.sonos/META-INF/MANIFEST.MF:
  Require-Bundle: org.apache.httpcomponents.httpclient;bundle-version="4.1.0",
   org.apache.httpcomponents.httpcore;bundle-version="4.1.0"
openhab/bundles/io/org.openhab.io.caldav/lib/httpclient-4.3.5.jar
openhab/bundles/io/org.openhab.io.caldav/lib/httpcore-4.3.2.jar
openhab-core/targetplatform/openhab.target:<unit id="org.apache.httpcomponents.httpclient" version="4.2.6.v201311072007"/>
openhab-core/targetplatform/openhab.target:<unit id="org.apache.httpcomponents.httpcore" version="4.2.5.v201311072007"/>
openhab-core/targetplatform/openhab.target:<unit id="org.apache.httpcomponents.httpcore.nio" version="4.1.0.v201101201700"/>
openhab2-addons/addons/binding/org.openhab.binding.freebox/lib/httpclient-4.3.1.jar 
openhab2-addons/addons/binding/org.openhab.binding.freebox/lib/httpcore-4.3.jar 
openhab2-addons/addons/binding/org.openhab.binding.freebox/lib/httpmime-4.3.1.jar 
```

**Comment by kaikreuzer** [comment]
Oh hell...
Yes, this might be an option, too.
And your list shows clearly that the new dependency management of Karaf brings a huge value :-)

**Comment by sipvoip** [comment]
Noticed this has sat for a while, any plans to support Insteon PLM on OpenHab2?

**Comment by robnielsen** [comment]
It worked when I tried it with a PLM, this error occurs when you use a hub.

**Comment by mafiat** [comment]
can any one help me here. How do we configure PLM instead of HUB to get this working?

**Comment by mafiat** [comment]
Hi Kai and watou, Can you shed some light how we fix this? I was on OH2 and had to go to OH1 because cant get Insteon working. Thanks,

**Comment by watou** [comment]
Please try the test JAR link in #4573.

**Comment by craigham** [comment]
As I look into this, I fear there is more to the problem.  

After reading the following discussion, which version of Java can also play a part in a solution.  What is the expected version of the jdks to be supported for the 1.8 line, and 2 ?  I imagine the apache http client lib  must be used all over the place.  Is manually adding that jar to all those bindings not going to cause issues?  It's really working around the motivations behind OSGI as I know it.

http://stackoverflow.com/questions/15336477/deprecated-java-httpclient-how-hard-can-it-be

I'm unfamiliar with the compat layer, but is this a case of somewhere that it comes up short?  This particular binding has had hardly any real activity in terms of new code/features since Oct/15.  When would it make sense to stop trying to be compatible for both 1.x and the 2 line?      

I'm not trying to come across as I know more than anyone.  These are just questions that I come up with when I tried to come up with a solution, and I feel I need a little more to be helpful, and I would like to contribute.

**Comment by watou** [comment]
> It's really working around the motivations behind OSGI as I know it.

That's absolutely true, but the fact that the HTTP library lost backward compatibility is a real complication that would first need a fix external to the binding.  Kai suggested this fix earlier:

> We could package the version 4.1 with either the InsteonPLM binding feature or the compat1x feature. We would then require a version constraint on the package import to say that it must be <4.2, so that the OSGi framework resolves the correct version for the binding. This should hopefully work...

If you would prefer to implement a PR that implements his suggestion, it would probably be better than adding the library statically to the bundle, in which case I would close #4573.  (I don't mind at all.)

> I'm not trying to come across as I know more than anyone. These are just questions that I come up with when I tried to come up with a solution, and I feel I need a little more to be helpful, and I would like to contribute

I think it's great and your contributions, and your desire to contribute, are much appreciated.

**Comment by craigham** [comment]
I tried to take a look at HubIOStream, but I don't think I can make the changes to remove the deprecated reference.  

I took a look at the class, and just can't figure it out.  I'm missing how the input/output streams are connected to the http client.  I don't have a hub and considering my lack of understanding, I would really need one to make any changes.  

Hopefully someone else can take a look who has a hub.

**Comment by watou** [comment]
@kaikreuzer:
> We could package the version 4.1 with either the InsteonPLM binding feature or the compat1x feature. We would then require a version constraint on the package import to say that it must be <4.2, so that the OSGi framework resolves the correct version for the binding. This should hopefully work...

I believe this is the best solution.  I will add the correct version constraint to the binding's MANIFEST.MF, but could you, @kaikreuzer (or others who know how) add to the compat1x feature the versions that the binding imports under 1.x, so the newly added constraints resolve?  That way the same 1.x binding should continue to run under both openHAB 1.x and 2.x.

I proposed these constraints earlier:

```
 org.apache.http;version="[4.1,4.2)",
 org.apache.http.auth;version="[4.1,4.2)",
 org.apache.http.client;version="[4.1,4.2)",
 org.apache.http.client.methods;version="[4.1,4.2)",
 org.apache.http.impl.client;version="[4.1,4.2)",
 org.apache.http.params;version="[4.1,4.2)",
 org.apache.http.util;version="[4.1.4,4.2)",
```

but the final constraints are based on what specific versions are in 1.x, and I don't know where that is.  Thanks.

**Comment by kaikreuzer** [comment]
@watou As the http libs are quite fat, I would prefer to add them to the InsteonPLM feature rather than to the compat1x feature (which is installed for most people, even though they do not use any 1.x add-on that requires an http client lib).

**Comment by watou** [comment]
>  @kaikreuzer:  I would prefer to add them to the InsteonPLM feature

OK; I will work on that.

**Comment by larizzo** [comment]
@watou Were you able to make any progress on this? Is there a workaround we could use in the meantime? If there's something I can do to help please let me know.

**Comment by watou** [comment]
Sorry, no progress yet.  The problem is that Apache HttpClient 4.3 (present in OH2) is not backward compatible with 4.1 (present in OH1), and yet this binding has to work in both OH1 and OH2.  So the best solution appears to be to add a feature in OH2 that provides the 4.1 version, and add the version constraint in the InsteonPLM binding so it resolves the older libraries.  I haven't yet figured out how to add the feature for the old libraries.  Anything you can do on that front will help accelerate closing this issue.

**Comment by phutchins** [comment]
What do we need to do to get this going? I've been running OH1 previously and set up OH2 and realized that I can't use it to control my Insteon setup :(. I'd be glad to help if you can provide a little more detail on the changes needed. The new interface looks so nice! Cant wait to use it.

**Comment by jtmoderate876** [comment]
I moved to Insteon USB PLM - which doesn't use HTTPClient so it works, is also faster than HUB2014 and isn't constantly polling the hub over then network and bogging down the hub..

I still use the HUB for the occasional insteon app and Stringify.

**Comment by phutchins** [comment]
@jtmoderate876 which addon exactly is the one that you're using? This one https://github.com/openhab/openhab/wiki/Insteon-PLM-Binding ? I'm using the Insteon USB PLM as well but not sure which addon I should be using or how to install... Looks like I need to do everything without the UI if I'm doing it in OpenHAB2 vs OH1. Any tips or pointers on how you got it working?

**Comment by ThomDietrich** [comment]
I'm currently working on the list of openHAB 2.0 incompatible addons. Is this binding still making problems?

**Comment by watou** [comment]
> Is this binding still making problems?

Yes, still not fully working on OH2.

**Comment by wdesponts** [comment]
I've been looking at the source code on GIthub and noticed that the offending file is the HubIOStream.java file (Bundle-ClassPath: lib/httpcore-4.1.4.jar,).  

Because this file is only called when an Insteon Hub is in play, anyone using the simple PLMs (Serial or usb) will not be affected.

From what others have indicated the class called (org.apache.http.impl.client.DefaultHttpClient) is no longer available in in version 4.3 or higher of apache server.  Openhab2.0 uses this newer version and thus the old binding no longer works for Openhab2.

A solution was proposed to have the manifest file changed to call-up the old version of apache like was proposed by @watou.

"org.apache.http;version="[4.1,4.2)",
 org.apache.http.auth;version="[4.1,4.2)",
 org.apache.http.client;version="[4.1,4.2)",
 org.apache.http.client.methods;version="[4.1,4.2)",
 org.apache.http.impl.client;version="[4.1,4.2)",
 org.apache.http.params;version="[4.1,4.2)",
 org.apache.http.util;version="[4.1.4,4.2)",

However adding this to the "compat1x feature" as indicated by @kaikreuzer is not advisable and we should therefore add the http libs in the InsteonPLM binding instead.

To that end I noticed that someone added the "Bundle-ClassPath: lib/httpcore-4.1.4.jar," to the manifest as well ad added it to the lib for the biding.  

What I think may be missing is the link or argument in "HubIOStream.java file (Bundle-ClassPath: lib/httpcore-4.1.4.jar," that tells the system to use the old version version of http instead of the new one.  or possibly the manifest need to be amended to what @watou  suggested.

I'd love to try things out but try as I might I can't get the development environment installed on my workstation nor can i create a new jar file to test, I can only offer to test, test and re-test until a solution is found.  I now have both a OpenHab1 and OpenHab2 lab environment.

**Comment by robnielsen** [comment]
@wdesponts I finally got a dev  environment up and working again, but I only have a PLM. I'll contact you offline from the openhab community and create some test builds for you to try out.

**Comment by phutchins** [comment]
I'm going to try to install it manually but I was unable to get to install and show up through the interface. Should that be working now? 

On December 7, 2016 5:12:38 PM EST, Thomas Dietrich <notifications@github.com> wrote:
>I'm currently working on the list of openHAB 2.0 incompatible addons.
>Is this binding still making problems?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openhab/openhab/issues/3922#issuecomment-265589930

--

**Comment by larizzo** [comment]
@robnielsen I'd like to help test also if you don't mind including me. I have both 1.8.3 and 2 setup.

**Comment by robnielsen** [comment]
@larizzo I'll also contact you offline via the openhab community.

**Comment by robnielsen** [comment]
@larizzo, I appears that the defect https://github.com/openhab/openhab/issues/4630 is bascially the same defect as this one? If so, it looks like the issue has moved to another missing jar file for org.apache.commons.logging in MANIFEST.MF

**Comment by robnielsen** [comment]
@wdesponts, @larizzo, I think I have a fix. I don't have a hub, but used a dummy hostname and am getting the following in the log file with OH2:

`2016-12-20` 20:42:38.528 [ERROR] [nplm.internal.driver.hub.HubIOStream] - got exception while polling: org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:25105 refused

Please try the binding at https://www.dropbox.com/s/93aokmorc0i2ed8/org.openhab.binding.insteonplm-1.9.0-SNAPSHOT.jar?dl=0 and let me know how it goes. Make sure you uninstall the any other insteonplm bindings before you try this one.

**Comment by ThomDietrich** [comment]
Thanks @robnielsen.

**Comment by phutchins** [comment]
I'd like to help test as well. I've had 1.8.3 and 2 setups and am rebuilding them now all in docker.

I've gotten it all set up from the console but not any of the UI's...
